name: Compile LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find and compile LaTeX files
      run: |
        find . -regex './Ue[0-9]+/main.tex' -execdir sh -c 'latexmk -pdf -jobname=$(basename $(pwd)) "$0"' {} \;
      env:
        TEXINPUTS: "./Macros//:"

    - name: Upload compiled PDFs
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdfs
        path: |
          **/*.pdf
